[[redirects]]
from = "/blog"
to = "https://cobraracingf1inschools.wordpress.com"
status = 200
force = true

[[redirects]]
from = "/contact/:splat"
to = "https://cobraracingf1inschools.wordpress.com/about"
status = 200
force = true
