[[redirects]]
    from = "/blog"
    to = "https://cobraracingf1inschools.wordpress.com"
    status = 200

    from = "/contact"
    to = "https://cobraracingf1inschools.wordpress.com/about"
    status = 200